jwt:
  secret-key: abcdefghijklmnopqrstuvwxyz0123456789
  token:
    expired-time-ms: 3000000
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/HR_system
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.show_sql: true
      hibernate.format_sql: true


cloud:
  aws:
    s3:
      bucket: lch2023-s3
    credentials:
      access-key: AKIA2H67JGHVCOYRJA54
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
